import type { UniverseEntry } from "./types";

/**
 * The curated watch universe: ~36 companies riding major technology shifts.
 *
 * These are STARTING IDEAS, not recommendations. Each entry's static facts
 * (sector, theme, founder-led) are hand-curated and should be re-verified —
 * CEOs change. Live financials are fetched at runtime and drive the score.
 *
 * Add your own names here; the screener will pick them up automatically.
 */
export const UNIVERSE: UniverseEntry[] = [
  // ───────────── AI Infrastructure & Semiconductors ─────────────
  {
    ticker: "NVDA",
    name: "NVIDIA",
    themes: ["AI Infrastructure", "Semiconductors"],
    founderLed: true,
    founder: "Jensen Huang",
    blurb: "GPUs and the CUDA software stack powering modern AI training and inference.",
    thesis: "Proven winner / benchmark — included so you can compare emerging names against an obvious one.",
  },
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    themes: ["AI Infrastructure", "Defense Tech"],
    founderLed: true,
    founder: "Alex Karp",
    blurb: "Data/AI operating systems for government and large enterprises.",
    thesis: "Category creator bridging defense and commercial AI; founder-led with accelerating commercial growth.",
  },
  {
    ticker: "CRWV",
    name: "CoreWeave",
    themes: ["AI Infrastructure"],
    founderLed: true,
    founder: "Michael Intrator",
    blurb: "Specialized GPU cloud built for AI workloads.",
    thesis: "Picks-and-shovels capacity for the AI buildout; explosive revenue, heavy capex to watch.",
  },
  {
    ticker: "NBIS",
    name: "Nebius Group",
    themes: ["AI Infrastructure"],
    founderLed: true,
    founder: "Arkady Volozh",
    blurb: "AI-centric cloud infrastructure provider spun out of Yandex's international assets.",
    thesis: "Founder-led AI cloud with a clean balance sheet and a large addressable compute market.",
  },
  {
    ticker: "ALAB",
    name: "Astera Labs",
    themes: ["Semiconductors", "AI Infrastructure"],
    founderLed: true,
    founder: "Jitendra Mohan",
    blurb: "Connectivity silicon (retimers, smart cabling) that wires up AI data centers.",
    thesis: "High-margin enabler of AI rack-scale interconnect; small relative to the trend it serves.",
  },
  {
    ticker: "SMCI",
    name: "Super Micro Computer",
    themes: ["AI Infrastructure"],
    founderLed: true,
    founder: "Charles Liang",
    blurb: "Builds high-density, energy-efficient AI servers and rack systems.",
    thesis: "Founder-led hardware vendor levered to AI server demand; watch margins and governance.",
  },

  // ───────────── Robotics & Automation ─────────────
  {
    ticker: "SYM",
    name: "Symbotic",
    themes: ["Robotics & Automation"],
    founderLed: true,
    founder: "Rick Cohen",
    blurb: "AI-powered warehouse automation systems for large retailers.",
    thesis: "Founder-led category leader automating the physical supply chain; large backlog.",
  },
  {
    ticker: "PATH",
    name: "UiPath",
    themes: ["Robotics & Automation", "AI Infrastructure"],
    founderLed: true,
    founder: "Daniel Dines",
    blurb: "Robotic process automation and AI agents for enterprise workflows.",
    thesis: "Founder returned as CEO; pivoting RPA toward agentic AI with software-like margins.",
  },
  {
    ticker: "SERV",
    name: "Serve Robotics",
    themes: ["Robotics & Automation"],
    founderLed: true,
    founder: "Ali Kashani",
    blurb: "Autonomous sidewalk delivery robots.",
    thesis: "Early, speculative robotics name entering a potentially huge last-mile market — high risk.",
  },

  // ───────────── Defense Tech ─────────────
  {
    ticker: "RCAT",
    name: "Red Cat Holdings",
    themes: ["Defense Tech", "Robotics & Automation"],
    founderLed: true,
    founder: "Jeff Thompson",
    blurb: "Military drone systems and components.",
    thesis: "Small-cap drone play levered to Western defense restocking; lumpy contract-driven revenue.",
  },
  {
    ticker: "KTOS",
    name: "Kratos Defense & Security",
    themes: ["Defense Tech"],
    founderLed: false,
    blurb: "Unmanned systems, drones, and propulsion for defense.",
    thesis: "Established defense-tech mid-cap riding autonomous-systems budgets.",
  },
  {
    ticker: "AVAV",
    name: "AeroVironment",
    themes: ["Defense Tech", "Robotics & Automation"],
    founderLed: false,
    blurb: "Small unmanned aircraft and loitering munitions.",
    thesis: "Pure-play tactical drone vendor with growing international demand.",
  },

  // ───────────── Energy Storage ─────────────
  {
    ticker: "AMPX",
    name: "Amprius Technologies",
    themes: ["Energy Storage"],
    founderLed: true,
    founder: "Kang Sun",
    blurb: "High-energy-density silicon-anode batteries.",
    thesis: "Founder-led battery tech targeting aviation/defense niches first; pre-scale, speculative.",
  },
  {
    ticker: "ENPH",
    name: "Enphase Energy",
    themes: ["Energy Storage"],
    founderLed: false,
    blurb: "Microinverters and home battery/storage systems.",
    thesis: "Proven solar-storage winner — benchmark for what a scaled energy name looks like.",
  },
  {
    ticker: "EOSE",
    name: "Eos Energy Enterprises",
    themes: ["Energy Storage"],
    founderLed: false,
    blurb: "Zinc-based long-duration grid storage.",
    thesis: "Non-lithium grid storage bet; binary on manufacturing ramp and cash runway.",
  },

  // ───────────── Nuclear Power ─────────────
  {
    ticker: "OKLO",
    name: "Oklo",
    themes: ["Nuclear Power"],
    founderLed: true,
    founder: "Jacob DeWitte",
    blurb: "Small fast-fission reactors sold as a power service.",
    thesis: "Founder-led SMR with a build-own-operate model; pre-revenue, regulatory-gated, high beta.",
  },
  {
    ticker: "NNE",
    name: "Nano Nuclear Energy",
    themes: ["Nuclear Power"],
    founderLed: true,
    founder: "Jay Yu",
    blurb: "Microreactor designs and nuclear fuel transportation.",
    thesis: "Very early micro-cap nuclear concept; pure optionality, treat as a lottery slice.",
  },
  {
    ticker: "SMR",
    name: "NuScale Power",
    themes: ["Nuclear Power"],
    founderLed: false,
    blurb: "Licensed small modular reactor technology.",
    thesis: "Furthest-along SMR by regulatory approval; execution and customer commitments are the test.",
  },

  // ───────────── Digital Health ─────────────
  {
    ticker: "HIMS",
    name: "Hims & Hers Health",
    themes: ["Digital Health"],
    founderLed: true,
    founder: "Andrew Dudum",
    blurb: "Direct-to-consumer telehealth and personalized treatments.",
    thesis: "Founder-led consumer-health brand with accelerating revenue and improving cash flow.",
  },
  {
    ticker: "TEM",
    name: "Tempus AI",
    themes: ["Digital Health", "AI Infrastructure"],
    founderLed: true,
    founder: "Eric Lefkofsky",
    blurb: "AI-driven precision medicine and clinical/genomic data.",
    thesis: "Founder-led health-data platform compounding a proprietary clinical dataset.",
  },
  {
    ticker: "DOCS",
    name: "Doximity",
    themes: ["Digital Health"],
    founderLed: true,
    founder: "Jeff Tangney",
    blurb: "Professional network and workflow tools for U.S. physicians.",
    thesis: "Founder-led, highly profitable network with strong margins and a clear moat.",
  },
  {
    ticker: "RXRX",
    name: "Recursion Pharmaceuticals",
    themes: ["Digital Health", "AI Infrastructure"],
    founderLed: true,
    founder: "Chris Gibson",
    blurb: "AI-driven drug discovery at industrial scale.",
    thesis: "Founder-led techbio platform; pipeline is the payoff, cash burn is the risk.",
  },

  // ───────────── Cybersecurity ─────────────
  {
    ticker: "CRWD",
    name: "CrowdStrike",
    themes: ["Cybersecurity", "AI Infrastructure"],
    founderLed: true,
    founder: "George Kurtz",
    blurb: "Cloud-native endpoint and security platform.",
    thesis: "Proven winner / benchmark — the model of a founder-led, high-margin security compounder.",
  },
  {
    ticker: "ZS",
    name: "Zscaler",
    themes: ["Cybersecurity"],
    founderLed: true,
    founder: "Jay Chaudhry",
    blurb: "Cloud-delivered zero-trust network security.",
    thesis: "Founder-led zero-trust leader with durable growth and improving free cash flow.",
  },
  {
    ticker: "S",
    name: "SentinelOne",
    themes: ["Cybersecurity", "AI Infrastructure"],
    founderLed: true,
    founder: "Tomer Weingarten",
    blurb: "Autonomous AI-based endpoint protection.",
    thesis: "Founder-led CrowdStrike challenger; faster-growing but earlier on the margin curve.",
  },
  {
    ticker: "NET",
    name: "Cloudflare",
    themes: ["Cybersecurity", "AI Infrastructure"],
    founderLed: true,
    founder: "Matthew Prince",
    blurb: "Edge network for security, performance, and developer/AI infrastructure.",
    thesis: "Founder-led platform expanding from security into edge compute and AI inference.",
  },
  {
    ticker: "RBRK",
    name: "Rubrik",
    themes: ["Cybersecurity"],
    founderLed: true,
    founder: "Bipul Sinha",
    blurb: "Data security and cyber-resilience / backup platform.",
    thesis: "Founder-led data-security growth story; watch the path from growth to profitability.",
  },

  // ───────────── Space ─────────────
  {
    ticker: "RKLB",
    name: "Rocket Lab",
    themes: ["Space", "Defense Tech"],
    founderLed: true,
    founder: "Peter Beck",
    blurb: "Small-launch rockets, satellites, and space systems.",
    thesis: "Founder-led, vertically integrating toward a larger rocket; the clearest SpaceX-adjacent public bet.",
  },
  {
    ticker: "ASTS",
    name: "AST SpaceMobile",
    themes: ["Space"],
    founderLed: true,
    founder: "Abel Avellan",
    blurb: "Satellite-to-cellphone broadband direct from space.",
    thesis: "Founder-led, huge TAM if it works; capital-intensive and execution-binary.",
  },
  {
    ticker: "LUNR",
    name: "Intuitive Machines",
    themes: ["Space", "Defense Tech"],
    founderLed: true,
    founder: "Steve Altemus",
    blurb: "Lunar landers and cislunar services for NASA and commercial customers.",
    thesis: "Founder-led space-services play on NASA's return-to-moon spending; mission-risk lumpy.",
  },
  {
    ticker: "PL",
    name: "Planet Labs",
    themes: ["Space", "Defense Tech"],
    founderLed: true,
    founder: "Will Marshall",
    blurb: "Daily Earth-imaging satellite data and analytics.",
    thesis: "Founder-led data subscription business on top of a satellite constellation.",
  },

  // ───────────── Fintech / Payments ─────────────
  {
    ticker: "AFRM",
    name: "Affirm Holdings",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Max Levchin",
    blurb: "Buy-now-pay-later consumer lending and checkout.",
    thesis: "Founder-led consumer-credit network scaling toward GAAP profitability.",
  },
  {
    ticker: "TOST",
    name: "Toast",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Aman Narang",
    blurb: "Point-of-sale and payments software for restaurants.",
    thesis: "Founder-led vertical SaaS+payments compounder with a large under-penetrated market.",
  },
  {
    ticker: "NU",
    name: "Nu Holdings (Nubank)",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "David Vélez",
    blurb: "Digital bank serving Latin America.",
    thesis: "Founder-led, profitable hyper-growth bank with a massive emerging-market runway.",
  },
  {
    ticker: "BILL",
    name: "BILL Holdings",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "René Lacerte",
    blurb: "Accounts-payable/receivable automation for small businesses.",
    thesis: "Founder-led SMB fintech with payment-volume optionality; growth decel is the watch item.",
  },

  // ───────────── Expanded candidate pool ─────────────
  {
    ticker: "DDOG",
    name: "Datadog",
    themes: ["AI Infrastructure", "Cybersecurity"],
    founderLed: true,
    founder: "Olivier Pomel",
    blurb: "Cloud observability and security monitoring platform.",
    thesis: "Founder-led, high-margin platform expanding into AI/LLM observability.",
  },
  {
    ticker: "APP",
    name: "AppLovin",
    themes: ["AI Infrastructure"],
    founderLed: true,
    founder: "Adam Foroughi",
    blurb: "AI-driven mobile advertising and app-monetization engine.",
    thesis: "Founder-led; its AI ad engine drove explosive, high-margin growth.",
  },
  {
    ticker: "SOUN",
    name: "SoundHound AI",
    themes: ["AI Infrastructure"],
    founderLed: true,
    founder: "Keyvan Mohajer",
    blurb: "Voice and conversational-AI platform for cars, restaurants, devices.",
    thesis: "Founder-led pure-play voice AI; fast growth but still small and cash-burning.",
  },
  {
    ticker: "CRDO",
    name: "Credo Technology",
    themes: ["Semiconductors", "AI Infrastructure"],
    founderLed: true,
    founder: "Bill Brennan",
    blurb: "High-speed connectivity (SerDes, active cables) for AI data centers.",
    thesis: "Founder-led interconnect supplier riding AI bandwidth demand.",
  },
  {
    ticker: "INDI",
    name: "indie Semiconductor",
    themes: ["Semiconductors", "Robotics & Automation"],
    founderLed: true,
    founder: "Donald McClymont",
    blurb: "Chips for automotive ADAS, sensing, and connectivity.",
    thesis: "Founder-led auto-semi rollup levered to vehicle autonomy; watch the path to profit.",
  },
  {
    ticker: "AEVA",
    name: "Aeva Technologies",
    themes: ["Robotics & Automation"],
    founderLed: true,
    founder: "Soroush Salehian",
    blurb: "Frequency-modulated (FMCW) lidar for autonomy and industrial sensing.",
    thesis: "Founder-led lidar bet; differentiated tech but pre-scale and speculative.",
  },
  {
    ticker: "KSCP",
    name: "Knightscope",
    themes: ["Robotics & Automation", "Defense Tech"],
    founderLed: true,
    founder: "William Santana Li",
    blurb: "Autonomous security robots and emergency communication devices.",
    thesis: "Founder-led security-robotics micro-cap; lottery-ticket risk profile.",
  },
  {
    ticker: "NVTS",
    name: "Navitas Semiconductor",
    themes: ["Semiconductors", "Energy Storage"],
    founderLed: true,
    founder: "Gene Sheridan",
    blurb: "Gallium-nitride and silicon-carbide power chips for fast charging and AI power.",
    thesis: "Founder-led next-gen power semis levered to AI data-center power and EVs.",
  },
  {
    ticker: "ONDS",
    name: "Ondas Holdings",
    themes: ["Defense Tech", "Robotics & Automation"],
    founderLed: true,
    founder: "Eric Brock",
    blurb: "Industrial drones and private wireless networks.",
    thesis: "Founder-led drone/networking micro-cap; contract-driven and speculative.",
  },
  {
    ticker: "DRS",
    name: "Leonardo DRS",
    themes: ["Defense Tech"],
    founderLed: false,
    blurb: "Defense electronics, sensing, and power systems.",
    thesis: "Established defense-electronics supplier with steady program growth.",
  },
  {
    ticker: "NRGV",
    name: "Energy Vault",
    themes: ["Energy Storage"],
    founderLed: true,
    founder: "Robert Piconi",
    blurb: "Gravity- and battery-based long-duration energy storage.",
    thesis: "Founder-led storage bet; execution- and financing-dependent.",
  },
  {
    ticker: "FLNC",
    name: "Fluence Energy",
    themes: ["Energy Storage"],
    founderLed: false,
    blurb: "Grid-scale battery storage systems and software.",
    thesis: "Scaled grid-storage integrator; margins and competition are the watch items.",
  },
  {
    ticker: "LTBR",
    name: "Lightbridge",
    themes: ["Nuclear Power"],
    founderLed: true,
    founder: "Seth Grae",
    blurb: "Advanced nuclear fuel technology for existing and new reactors.",
    thesis: "Founder-led, pre-revenue nuclear-fuel optionality; very speculative.",
  },
  {
    ticker: "ASPI",
    name: "ASP Isotopes",
    themes: ["Nuclear Power"],
    founderLed: true,
    founder: "Paul Mann",
    blurb: "Enriched isotopes for nuclear fuel, medicine, and semiconductors.",
    thesis: "Founder-led isotope-enrichment play on the nuclear and HALEU supply gap.",
  },
  {
    ticker: "LEU",
    name: "Centrus Energy",
    themes: ["Nuclear Power"],
    founderLed: false,
    blurb: "Uranium enrichment, including domestic HALEU for advanced reactors.",
    thesis: "Key Western enrichment supplier levered to nuclear fuel reshoring.",
  },
  {
    ticker: "PHR",
    name: "Phreesia",
    themes: ["Digital Health"],
    founderLed: true,
    founder: "Chaim Indig",
    blurb: "Patient intake, scheduling, and payments software for healthcare.",
    thesis: "Founder-led health-IT compounder nearing sustained profitability.",
  },
  {
    ticker: "GH",
    name: "Guardant Health",
    themes: ["Digital Health"],
    founderLed: true,
    founder: "Helmy Eltoukhy",
    blurb: "Blood-based (liquid biopsy) cancer testing and screening.",
    thesis: "Founder-led precision-oncology platform with a large screening TAM.",
  },
  {
    ticker: "NTRA",
    name: "Natera",
    themes: ["Digital Health"],
    founderLed: false,
    blurb: "Genetic testing across reproductive, oncology, and organ health.",
    thesis: "Fast-growing diagnostics leader scaling test volumes and margins.",
  },
  {
    ticker: "OKTA",
    name: "Okta",
    themes: ["Cybersecurity"],
    founderLed: true,
    founder: "Todd McKinnon",
    blurb: "Identity and access management for workforce and customers.",
    thesis: "Founder-led identity leader; re-accelerating with improving free cash flow.",
  },
  {
    ticker: "VRNS",
    name: "Varonis Systems",
    themes: ["Cybersecurity"],
    founderLed: true,
    founder: "Yaki Faitelson",
    blurb: "Data-security platform protecting and monitoring sensitive data.",
    thesis: "Founder-led data-security name mid-transition to a SaaS model.",
  },
  {
    ticker: "TENB",
    name: "Tenable Holdings",
    themes: ["Cybersecurity"],
    founderLed: false,
    blurb: "Vulnerability management and exposure-management platform.",
    thesis: "Established exposure-management vendor with steady, profitable growth.",
  },
  {
    ticker: "RDW",
    name: "Redwire",
    themes: ["Space", "Defense Tech"],
    founderLed: false,
    blurb: "Space infrastructure: components, structures, and in-space manufacturing.",
    thesis: "Space-infrastructure rollup levered to defense and commercial space spend.",
  },
  {
    ticker: "MELI",
    name: "MercadoLibre",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Marcos Galperin",
    blurb: "Latin American e-commerce and fintech (Mercado Pago) ecosystem.",
    thesis: "Founder-led compounder pairing dominant e-commerce with a scaling fintech.",
  },
  {
    ticker: "UPST",
    name: "Upstart Holdings",
    themes: ["Fintech / Payments", "AI Infrastructure"],
    founderLed: true,
    founder: "Dave Girouard",
    blurb: "AI-based consumer lending marketplace.",
    thesis: "Founder-led AI-lending platform; high upside but rate- and credit-cycle sensitive.",
  },
  {
    ticker: "PAY",
    name: "Paymentus Holdings",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Dushyant Sharma",
    blurb: "Cloud bill-payment platform for billers and financial institutions.",
    thesis: "Founder-led, profitable bill-pay compounder with strong volume growth.",
  },
  {
    ticker: "RELY",
    name: "Remitly Global",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Matt Oppenheimer",
    blurb: "Digital cross-border remittances for immigrants.",
    thesis: "Founder-led remittance disruptor scaling toward durable profitability.",
  },
  {
    ticker: "GLBE",
    name: "Global-e Online",
    themes: ["Fintech / Payments"],
    founderLed: true,
    founder: "Amir Schlachet",
    blurb: "Cross-border e-commerce enablement (payments, duties, localization).",
    thesis: "Founder-led picks-and-shovels for international D2C commerce.",
  },
  {
    ticker: "SOFI",
    name: "SoFi Technologies",
    themes: ["Fintech / Payments"],
    founderLed: false,
    blurb: "Digital one-stop bank: lending, investing, and financial services.",
    thesis: "Fast-growing digital bank now consistently profitable; valuation is the debate.",
  },
];

export const TICKERS = UNIVERSE.map((u) => u.ticker);

export function getEntry(ticker: string): UniverseEntry | undefined {
  return UNIVERSE.find((u) => u.ticker.toUpperCase() === ticker.toUpperCase());
}

/** All distinct themes present in the universe, in a stable display order. */
export const ALL_THEMES = Array.from(
  new Set(UNIVERSE.flatMap((u) => u.themes)),
).sort();
